name: DiscordConnectorPlugin
version: 1.0.0
main: io.github.ariuan.connectorPlugin.ConnectorPlugin
description: An connection plugin
author: Ariuan
website: https://github.com/irisariuan
api-version: '1.21.4'
commands:
  cancelstop:
    description: Cancel a scheduled server shutdown
    usage: /cancelstop
    permission: connector.cancelstop
permissions:
  connector.cancelstop:
    description: Allows cancelling scheduled server shutdowns
    default: op